import type { Metadata } from "next";
// import { ClerkProvider } from '@clerk/nextjs'
import { JetBrains_Mono } from "next/font/google";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import Loading from "@/components/loading";


const jetbrains = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      
      <html lang="en">
        <ClerkProvider>
           
            
        <body className={jetbrains.className}>
          <Toaster toastOptions={{
            style: {
              borderRadius: '8px',
              background: '#333',
              color: '#fff',
              padding: '16px',
            }
          
          }}/>
           <ClerkLoading>
              <Loading/>
            </ClerkLoading>
          <ClerkLoaded>
            <div className="flex flex-col min-h-screen">
             <Navbar />
             <div className="flex-grow">
              {children}
             </div>
            
            <Footer />
          </div>
          </ClerkLoaded>
          
         
          </body>
          </ClerkProvider>
      </html>
      
    
    
  );
}
